name: Wheels

on:
  workflow_dispatch:
    inputs:
      filter:
        description: 'Only build specific platforms (regex)'
        required: false
        default: ''
        type: string
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9a-z]+"
    branches:
      - "**"

permissions:
  contents: read

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # NOTE: this should not be recursive, we really don't want to bundle vcpkg
          submodules: true

      - name: Build SDist
        run: pipx run build --sdist

      - name: Check metadata
        run: pipx run twine check dist/*

      - uses: actions/upload-artifact@v7
        with:
          name: dist-sdist
          path: dist/*.tar.gz

  generate_matrix:
    name: Generate OS matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.script.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: scripts/
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Run python matrix script
        id: script
        env:
          # use default (and reasonably fast) platforms if branch push, use input if workflow_dispatch
          PLATFORM_FILTER: |-
            ${{
              (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/'))
              && 'ubuntu-latest-native|windows-latest|macos-latest'
              || inputs.filter
            }}
        run: |
          echo "matrix=$(python ./scripts/ci/generate_os_matrix.py)" >> $GITHUB_OUTPUT

  build_wheels:
    name: Wheels (${{ matrix.display-name }})
    runs-on: ${{ matrix.os }}
    needs: generate_matrix
    strategy:
      fail-fast: false
      matrix:
        # entries are {os: *, arch: *, libc: *, crypto: *, display-name: *, artifact-tag: *}
        include: ${{ fromJSON(needs.generate_matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Unshallow vcpkg submodule
        run: git -C libdave/cpp/vcpkg fetch --unshallow

      - uses: ./.github/actions/prepare-vcpkg
        with:
          os-arch-key: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.libc }}
          crypto: ${{ matrix.crypto }}
          cache-dir: ${{ github.workspace }}/vcpkg_cache

      - name: Set up QEMU
        if: runner.os == 'Linux' && matrix.arch != 'native'
        uses: docker/setup-qemu-action@v4
        with:
          platforms: all

      - uses: pypa/cibuildwheel@v3.4.1
        env:
          # choose manylinux/musllinux (they are split for the sake of ci speedup)
          CIBW_BUILD: ${{ matrix.libc == 'glibc' && '*manylinux*' || (matrix.libc == 'musl' && '*musllinux*' || '') }}
          CIBW_ARCHS: ${{ matrix.arch }}

      # TODO: add another step to fail CI if .pyi changed in wheels?
      - name: Verify clean directory
        run: git diff --exit-code -- ":^src/**/*.pyi"

      - name: Upload wheels
        uses: actions/upload-artifact@v7
        with:
          path: wheelhouse/*.whl
          name: dist-${{ matrix.artifact-tag }}

  release_github:
    name: Release GitHub
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - build_sdist
      - build_wheels
    runs-on: ubuntu-latest
    permissions:
      contents: write  # required for creating releases

    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda  # v3.0.0
        with:
          files: dist/*
          draft: true
          body: |
            TBD

            **Changelog**: https://github.com/${{ github.repository }}/blob/main/docs/CHANGELOG.md#vTODO
            **Git history**: https://github.com/${{ github.repository }}/compare/vTODO...vTODO

  release_pypi:
    name: Release PyPI
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - build_sdist
      - build_wheels
    runs-on: ubuntu-latest

    environment:
      name: release-pypi
    permissions:
      id-token: write  # this permission is mandatory for trusted publishing

    steps:
      - uses: actions/setup-python@v6
      - uses: actions/download-artifact@v8
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b  # v1.14.0
        with:
          print-hash: true
